{{- if and .Values.cluster.networkPolicy.enabled (eq .Values.cluster.networkPolicy.provider "kubernetes") .Values.rbe.buildfarm.enabled }}
# Buildfarm server ingress
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "rek8s.fullname" . }}-buildfarm-server-ingress
  namespace: {{ .Values.namespaces.rbe }}
  labels:
    {{- include "rek8s.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: buildfarm-server
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 8980
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.namespaces.monitoring | quote }}
      ports:
        - protocol: TCP
          port: 9090
---
# Buildfarm worker ingress
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "rek8s.fullname" . }}-buildfarm-worker-ingress
  namespace: {{ .Values.namespaces.rbe }}
  labels:
    {{- include "rek8s.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: buildfarm-worker
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: buildfarm-worker
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: buildfarm-exec-worker
      ports:
        - protocol: TCP
          port: 8982
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.namespaces.monitoring | quote }}
      ports:
        - protocol: TCP
          port: 9090
---
# Redis ingress
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "rek8s.fullname" . }}-buildfarm-redis-ingress
  namespace: {{ .Values.namespaces.rbe }}
  labels:
    {{- include "rek8s.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: redis
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: buildfarm-server
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: buildfarm-worker
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: buildfarm-exec-worker
      ports:
        - protocol: TCP
          port: 6379
{{- end }}
