{{- if and .Values.cluster.ingress.enabled (eq .Values.cluster.ingress.provider "contour") .Values.bes.buildbuddy.enabled }}
# Contour HTTPProxy for BuildBuddy -- HTTP UI
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: {{ include "rek8s.fullname" . }}-bes-http
  namespace: {{ .Values.namespaces.bes }}
  labels:
    {{- include "rek8s.labels" . | nindent 4 }}
  {{- with .Values.cluster.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  virtualhost:
    fqdn: {{ include "rek8s.bes.hostname" . }}
    {{- if .Values.global.tls.enabled }}
    tls:
      secretName: {{ include "rek8s.fullname" . }}-bes-tls
      minimumProtocolVersion: "1.2"
    {{- end }}
  routes:
    - conditions:
        - prefix: /
      services:
        - name: {{ include "rek8s.fullname" . }}-buildbuddy
          port: {{ .Values.bes.buildbuddy.service.httpPort }}
---
# Contour HTTPProxy for BuildBuddy -- gRPC (BES + Remote Cache)
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: {{ include "rek8s.fullname" . }}-bes-grpc
  namespace: {{ .Values.namespaces.bes }}
  labels:
    {{- include "rek8s.labels" . | nindent 4 }}
  {{- with .Values.cluster.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  virtualhost:
    fqdn: {{ include "rek8s.bes.grpcHostname" . }}
    {{- if .Values.global.tls.enabled }}
    tls:
      secretName: {{ include "rek8s.fullname" . }}-bes-grpc-tls
      minimumProtocolVersion: "1.2"
    {{- end }}
  routes:
    - conditions:
        - prefix: /
      services:
        - name: {{ include "rek8s.fullname" . }}-buildbuddy
          port: {{ .Values.bes.buildbuddy.service.grpcPort }}
          protocol: h2c
      timeoutPolicy:
        response: 1h
        idle: 600s
{{- end }}
