name: Lint

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "charts/**"
      - "docs/**"
      - "examples/**"
      - "lefthook.yml"
      - "tools/lint/**"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "charts/**"
      - "docs/**"
      - "examples/**"
      - "lefthook.yml"
      - "tools/lint/**"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  yaml:
    name: YAML
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Lint YAML files
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # v3.1.1
        with:
          file_or_dir: "."
          config_file: tools/lint/yamllint.yml

  actions:
    name: GitHub Actions
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version: "1.25.x"
          cache: false

      - name: Install actionlint
        run: go install github.com/rhysd/actionlint/cmd/actionlint@v1.7.7

      - name: Run actionlint
        run: actionlint -config-file tools/lint/actionlint.yml
